name: Test Next.js App
on:
  push:
    branches:
      - frontend
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Verify Installation
        run: npm install && echo $npm_PACKAGE_LOCKFILE | base64 --decode | sh

      - name: Test Application
        run: npm run test
